console.log("\tSYSTEM")
console.log("Platform: ", process.platform)
console.log("Platform: ", process.arch)
console.log("Platform: ", process.platform)
console.log("\n\tNodeJS")
console.log("Node Version: ", process.version)
console.log("V8 Version", process.versions.v8)
console.log("LibUV Version", process.versions.uv)
console.log("\n\tProcess")
console.log("PID: ", process.pid)
console.log("title: ", process.title)
console.log("Current Dir: ", process.cwd())